name: build-push-deploy-to-gcp.yml

on:
    push:
        branches:
            - '**'
    workflow_dispatch:
      inputs:
        deploy_prod:
          description: 'Deploy to production'
          type: boolean
          required: false
          default: false

permissions: {}

jobs:
    build-push-docker-image:
        name: build-push-docker-image
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}
        permissions:
            packages: 'write'
            contents: 'read'
            id-token: 'write'
        steps:
            - uses: actions/checkout@v6
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v6.0.0
              with:
                  node-version: '24.x'
            - name: install-deps-client-and-server
              run: npm ci
            - name: lint-and-typecheck
              run: npm run lint-and-typecheck
            - name: build-client
              run: npm run build
            - name: build-server
              working-directory: server
              run: npm run build
            - name: docker-login
              if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and publish Docker image
              if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
              uses: nais/docker-build-push@v0
              id: docker-build-push
              with:
                  docker_context: .
                  team: supstonad
                  salsa: false
                  image_suffix: app # hvis denne endres så må prod-deploy oppdateres likt
                  tag: ${{ github.sha }}

    deploy-to-dev-gcp:
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
        name: deploy-to-dev-gcp
        permissions:
            contents: read
            id-token: write
        needs: build-push-docker-image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/dev-gcp.yaml
                  VAR: image=${{ needs.build-push-docker-image.outputs.image }}

    deploy-to-prod:
        needs: build-push-docker-image
        if: ${{ inputs.deploy_prod == true && github.ref == 'refs/heads/master' }}
        name: Deploy to prod gcp
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: prod-gcp
                  RESOURCE: .nais/prod-gcp.yaml
                  VAR: image=${{ needs.build-push-docker-image.outputs.image }}

    generate-draft-release:
        if: (github.ref == 'refs/heads/master')
        name: Generate/update draft release
        runs-on: ubuntu-latest
        permissions:
            contents: 'write' # needed to create/edit releases
            pull-requests: 'write' # needed to add labels to pull requests
        steps:
            # Drafts your next Release notes as Pull Requests are merged into "master"
            - uses: release-drafter/release-drafter@v6
              #with:
              # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
              # config-name: my-config.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
